# Python Programming Basics

Welcome to the first module of our coding course! In this notebook, we'll cover the fundamental building blocks of Python programming:

1. **Importing Libraries** - Using external packages like NumPy and Pandas
2. **Python Data Types** - Lists, tuples, dictionaries, sets, and arrays
3. **Loops** - For loops and While loops
4. **Conditional Statements** - If, elif, else
5. **Loop Control** - Break and Continue statements
6. **User-Defined Functions** - Creating reusable code blocks
7. **Classes** - Object-Oriented Programming basics

Let's dive in! 🐍


---

## 1. Importing Libraries

Python's power comes from its extensive ecosystem of libraries. Libraries are collections of pre-written code that provide useful functionality.

### Common Ways to Import Libraries

There are several ways to import libraries in Python:


In [1]:
# Method 1: Import the entire library
import numpy

# Method 2: Import with an alias (most common for numpy and pandas)
import numpy as np
import pandas as pd

# Method 3: Import specific functions from a library
from math import sqrt, pi

# Method 4: Import everything from a library (not recommended for large libraries)
from math import *

print("Libraries imported successfully!")


Libraries imported successfully!


### Using NumPy

NumPy is the fundamental package for numerical computing in Python.


In [5]:
# Creating arrays with NumPy
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

# Useful NumPy functions
print("\nMean:", np.mean(array_1d))
print("Sum:", np.sum(array_1d))
print("Standard Deviation:", np.std(array_1d))

# Generate arrays
zeros = np.zeros(5)
ones = np.ones(3)
range_array = np.arange(0, 11, 1)  # Start, stop, step

print("\nZeros:", zeros)
print("Ones:", ones)
print("Range:", range_array)


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]

Mean: 3.0
Sum: 15
Standard Deviation: 1.4142135623730951

Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1.]
Range: [ 0  1  2  3  4  5  6  7  8  9 10]


### Using Pandas

Pandas is the go-to library for data manipulation and analysis.


In [7]:
# Creating a DataFrame from a dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}

df = pd.DataFrame(data)
print("DataFrame:")
print(df)

# Basic DataFrame operations
print("\nDataFrame Info:")
print(f"Shape: {df.shape}")
print(f"Columns: {list(df.columns)}")

# Accessing data
print("\nAges column:")
print(df['Age'])

print("\nFirst 2 rows:")
print(df.head(3))


DataFrame:
      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    Diana   28      Houston

DataFrame Info:
Shape: (4, 3)
Columns: ['Name', 'Age', 'City']

Ages column:
0    25
1    30
2    35
3    28
Name: Age, dtype: int64

First 2 rows:
      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [8]:
import os

# Path to a CSV on your Desktop
desktop = os.path.join(os.path.expanduser("~"), "Desktop")
filepath = os.path.join(desktop, "test.csv")

df.to_csv(filepath, index=False)

In [4]:
import pandas as pd
import os

desktop = os.path.join(os.path.expanduser("~"), "Desktop")
filepath = os.path.join(desktop, "test.csv")

df = pd.read_csv(filepath)

In [5]:
df.head(3)

Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

---

## 2. Python Data Types

Python has several built-in data types. Understanding these is fundamental to programming effectively.

### Primitive Data Types


In [ ]:
# Integer (int) - whole numbers
age = 25.0
count = -10
print(f"Integer: {age}, type: {type(age)}")

# Float - decimal numbers
price = 19.99
price2 = 3/4
temperature = -3.5
print(f"Float: {price}, type: {type(price)}")

# String (str) - text
name = "Alice"
message = 'Hello, World!'
print(f"String: {name}, type: {type(name)}")

# Boolean (bool) - True or False
is_active = True
is_empty = False
print(f"Boolean: {is_active}, type: {type(is_active)}")

# NoneType - represents absence of value
result = None
print(f"None: {result}, type: {type(result)}")


Integer: 25, type: <class 'int'>
Float: 19.99, type: <class 'float'>
String: Alice, type: <class 'str'>
Boolean: True, type: <class 'bool'>
None: None, type: <class 'NoneType'>


In [19]:
arr2 = np.array([0, 0, 0, 1, 1, 2], dtype=int)
arr2

array([0, 0, 0, 1, 1, 2])

In [20]:
arr_bool = arr2.astype(bool)
arr_bool

array([False, False, False,  True,  True,  True])

In [21]:
arr_bool.astype(int)

array([0, 0, 0, 1, 1, 1])

In [ ]:
age = 1

In [13]:
type(age)

float

In [14]:
sqrt(age)

5.0

In [8]:
float(age)

25.0

### Lists

Lists are **ordered**, **mutable** (changeable) collections that can hold items of different types. They are defined with square brackets `[]`.


In [ ]:
# Creating lists
fruits = ['apple', 'banana', 'cherry']
numbers = [1, 2, 3, 4, 5]
mixed = [1, 'hello', 3.14, True]  # Can mix types

print("Original list:", fruits)

# Accessing elements (0-indexed)
print(f"First element: {fruits[0]}")
print(f"Last element: {fruits[-1]}")

# Modifying elements (lists are mutable)
fruits[1] = 'blueberry'
print(f"After modification: {fruits}")

# List operations
fruits.append('dragonfruit')      # Add to end
print(f"After append: {fruits}")

fruits.insert(1, 'apricot')       # Insert at position
print(f"After insert: {fruits}")

removed = fruits.pop()            # Remove and return last item
print(f"Removed '{removed}': {fruits}")

# Slicing
print(f"First two: {fruits[:2]}")
print(f"Last two: {fruits[-2:]}")

# Length
print(f"List length: {len(fruits)}")


Original list: ['apple', 'banana', 'cherry']
First element: apple
Last element: cherry
After modification: ['apple', 'blueberry', 'cherry']
After append: ['apple', 'blueberry', 'cherry', 'dragonfruit']
After insert: ['apple', 'apricot', 'blueberry', 'cherry', 'dragonfruit']
Removed 'dragonfruit': ['apple', 'apricot', 'blueberry', 'cherry']
First two: ['apple', 'apricot']
Last two: ['blueberry', 'cherry']
List length: 4


In [25]:
fruits[1] = 'blueberry'
print(f"After modification: {fruits}")

After modification: ['apple', 'blueberry', 'cherry']


In [34]:
# List operations
# fruits.append('dragonfruit')      # Add to end
# print(f"After append: {fruits}")

# fruits.insert(1, 'apricot')       # Insert at position
# print(f"After insert: {fruits}")

removed = fruits.pop(-1)            # Remove and return last item
print(f"Removed '{removed}': {fruits}")

Removed 'cherry': ['apple', 'apricot', 'blueberry']


In [30]:
fruits

['apple', 'apricot', 'apricot', 'blueberry', 'cherry']

In [31]:
vegetables = ["lettuce", "kale"]

In [32]:
fruits + vegetables

['apple', 'apricot', 'apricot', 'blueberry', 'cherry', 'lettuce', 'kale']

### Tuples

Tuples are **ordered**, **immutable** (unchangeable) collections. They are defined with parentheses `()`. Use tuples when you want data that shouldn't be modified.


In [10]:
# Creating tuples
coordinates = (10, 20)
rgb_color = (255, 128, 0)
single_item = (42,)  # Note: comma needed for single-item tuple

print(f"Coordinates: {coordinates}, type: {type(coordinates)}")

# Accessing elements (same as lists)
print(f"X coordinate: {coordinates[0]}")
print(f"Y coordinate: {coordinates[1]}")

# Tuple unpacking - very useful!
x, y = coordinates
print(f"Unpacked - x: {x}, y: {y}")

r, g, b = rgb_color
print(f"RGB values - R: {r}, G: {g}, B: {b}")

# Tuples are immutable - this would cause an error:
# coordinates[0] = 15  # TypeError: 'tuple' object does not support item assignment

# But you can create a new tuple
new_coords = (15, coordinates[1])
print(f"New coordinates: {new_coords}")

# Common use: returning multiple values from functions
def get_dimensions():
    return (1920, 1080)  # Returns a tuple

width, height = get_dimensions()
print(f"Screen: {width}x{height}")


Coordinates: (10, 20), type: <class 'tuple'>
X coordinate: 10
Y coordinate: 20
Unpacked - x: 10, y: 20
RGB values - R: 255, G: 128, B: 0
New coordinates: (15, 20)
Screen: 1920x1080


In [35]:
# Creating tuples
coordinates = (10, 20)
rgb_color = (255, 128, 0)
single_item = (42,)  # Note: comma needed for single-item tuple

print(f"Coordinates: {coordinates}, type: {type(coordinates)}")

# Accessing elements (same as lists)
print(f"X coordinate: {coordinates[0]}")
print(f"Y coordinate: {coordinates[1]}")

# Tuple unpacking - very useful!
x, y = coordinates
print(f"Unpacked - x: {x}, y: {y}")

r, g, b = rgb_color
print(f"RGB values - R: {r}, G: {g}, B: {b}")

Coordinates: (10, 20), type: <class 'tuple'>
X coordinate: 10
Y coordinate: 20
Unpacked - x: 10, y: 20
RGB values - R: 255, G: 128, B: 0


In [36]:
coordinates[0] = 15  # TypeError: 'tuple' object does not support item assignment

TypeError: 'tuple' object does not support item assignment

### Dictionaries

Dictionaries store **key-value pairs**. They are **unordered** (in older Python) and **mutable**. Defined with curly braces `{}`. Keys must be unique and immutable.


In [44]:
# Creating dictionaries
person = {
    'name': 'Alice',
    'age': 30,
    'city': 'New York'
}

print(f"Person: {person}")
print(f"Type: {type(person)}")

# Accessing values by key
print(f"Name: {person['name']}")
print(f"Age: {person['age']}")

# Using .get() - safer, returns None if key doesn't exist
print(f"City: {person.get('city')}")
print(f"Country: {person.get('country', 'Not specified')}")  # Default value

# Modifying dictionaries
person['age'] = 31                    # Update existing key
person['email'] = 'alice@email.com'   # Add new key
print(f"Updated: {person}")

# Removing items
del person['city']
print(f"After delete: {person}")

# Useful dictionary methods
print(f"Keys: {list(person.keys())}")
print(f"Values: {list(person.values())}")
print(f"Items: {list(person.items())}")

# Check if key exists
print(f"'name' in person: {'name' in person}")
print(f"'city' in person: {'city' in person}")


Person: {'name': 'Alice', 'age': 30, 'city': 'New York'}
Type: <class 'dict'>
Name: Alice
Age: 30
City: New York
Country: Not specified
Updated: {'name': 'Alice', 'age': 31, 'city': 'New York', 'email': 'alice@email.com'}
After delete: {'name': 'Alice', 'age': 31, 'email': 'alice@email.com'}
Keys: ['name', 'age', 'email']
Values: ['Alice', 31, 'alice@email.com']
Items: [('name', 'Alice'), ('age', 31), ('email', 'alice@email.com')]
'name' in person: True
'city' in person: False


In [ ]:
# Creating dictionaries
person = {
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [30, 22, 28],
    'city': ['New York', 'Atlanta', 'Buenos Aires']
}

print(f"Person: {person}")
print(f"Type: {type(person)}")

# Accessing values by key
print(f"Name: {person['name']}")
print(f"Age: {person['age']}")

Person: {'name': 'Alice', 'age': 30, 'city': 'New York'}
Type: <class 'dict'>
Name: Alice
Age: 30


In [45]:
person = {
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [30, 22, 28],
    'city': ['New York', 'Atlanta', 'Buenos Aires']
}

df = pd.DataFrame(person)

In [46]:
df

name  age          city
0    Alice   30      New York
1      Bob   22       Atlanta
2  Charlie   28  Buenos Aires

In [39]:
person['city']

'New York'

In [40]:
person.get('city')


'New York'

In [43]:
person['country']

KeyError: 'country'

In [42]:
person.get('country')

In [41]:
print(f"Country: {person.get('country', 'Not specified')}")

Country: Not specified


### Sets

Sets are **unordered** collections of **unique** elements. They are **mutable** and defined with curly braces `{}` or `set()`. Great for removing duplicates and set operations.


In [12]:
# Creating sets
colors = {'red', 'green', 'blue'}
numbers = set([1, 2, 3, 3, 2, 1])  # Duplicates are removed!

print(f"Colors: {colors}")
print(f"Numbers (duplicates removed): {numbers}")

# Adding and removing elements
colors.add('yellow')
print(f"After add: {colors}")

colors.remove('red')  # Raises error if not found
print(f"After remove: {colors}")

colors.discard('purple')  # No error if not found
print(f"After discard: {colors}")

# Set operations
set_a = {1, 2, 3, 4}
set_b = {3, 4, 5, 6}

print(f"\nSet A: {set_a}")
print(f"Set B: {set_b}")
print(f"Union (A | B): {set_a | set_b}")           # All elements from both
print(f"Intersection (A & B): {set_a & set_b}")    # Common elements
print(f"Difference (A - B): {set_a - set_b}")      # Elements in A but not B

# Practical use: remove duplicates from a list
duplicates = [1, 2, 2, 3, 3, 3, 4]
unique = list(set(duplicates))
print(f"\nOriginal: {duplicates}")
print(f"Unique: {unique}")


Colors: {'green', 'red', 'blue'}
Numbers (duplicates removed): {1, 2, 3}
After add: {'yellow', 'green', 'red', 'blue'}
After remove: {'yellow', 'green', 'blue'}
After discard: {'yellow', 'green', 'blue'}

Set A: {1, 2, 3, 4}
Set B: {3, 4, 5, 6}
Union (A | B): {1, 2, 3, 4, 5, 6}
Intersection (A & B): {3, 4}
Difference (A - B): {1, 2}

Original: [1, 2, 2, 3, 3, 3, 4]
Unique: [1, 2, 3, 4]


In [47]:
colors = {'red', 'green', 'blue'}
numbers = set([1, 2, 3, 3, 2, 1])  # Duplicates are removed!

In [50]:
numbers

{1, 2, 3}

In [53]:
# Set operations
set_a = {1, 2, 3, 4}
set_b = {3, 4, 5, 6}

print(f"\nSet A: {set_a}")
print(f"Set B: {set_b}")
print(f"Union (A | B): {set_a | set_b}")           # All elements from both
print(f"Intersection (A & B): {set_a & set_b}")    # Common elements
print(f"Difference (A - B): {set_a - set_b}")
print(f"Difference (B - A): {set_b - set_a}")


Set A: {1, 2, 3, 4}
Set B: {3, 4, 5, 6}
Union (A | B): {1, 2, 3, 4, 5, 6}
Intersection (A & B): {3, 4}
Difference (A - B): {1, 2}
Difference (B - A): {5, 6}


### NumPy Arrays

NumPy arrays are **homogeneous** (all elements same type), **fixed-size** collections optimized for numerical operations. Much faster than lists for mathematical computations.


In [56]:
# NumPy arrays vs Python lists
python_list = [1, 2, 3, 4, 5]
numpy_array = np.array(python_list)

print(f"Python list: {python_list}, type: {type(python_list)}")
print(f"NumPy array: {numpy_array}, type: {type(numpy_array)}")

# Key difference: element-wise operations
print(f"\nList * 2: {python_list * 2}")       # Repeats the list
print(f"Array * 2: {numpy_array * 2}")        # Multiplies each element

# Mathematical operations on arrays
arr = np.array([10, 20, 30, 40])
print(f"\nOriginal array: {arr}")
print(f"Add 5: {arr + 5}")
print(f"Square root: {np.sqrt(arr)}")

# Multi-dimensional arrays
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(f"\n2D Array (matrix):\n{matrix}")
print(f"Shape: {matrix.shape}")  # (rows, columns)
print(f"Element at row 1, col 2: {matrix[1, 0]}")


Python list: [1, 2, 3, 4, 5], type: <class 'list'>
NumPy array: [1 2 3 4 5], type: <class 'numpy.ndarray'>

List * 2: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Array * 2: [ 2  4  6  8 10]

Original array: [10 20 30 40]
Add 5: [15 25 35 45]
Square root: [3.16227766 4.47213595 5.47722558 6.32455532]

2D Array (matrix):
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Element at row 1, col 2: 4


### Quick Comparison Table

| Type | Syntax | Ordered | Mutable | Duplicates | Use Case |
|------|--------|---------|---------|------------|----------|
| **List** | `[1, 2, 3]` | ✅ Yes | ✅ Yes | ✅ Allowed | General-purpose collection |
| **Tuple** | `(1, 2, 3)` | ✅ Yes | ❌ No | ✅ Allowed | Fixed data, dictionary keys |
| **Dictionary** | `{'a': 1}` | ✅ Yes* | ✅ Yes | Keys: ❌ | Key-value mappings |
| **Set** | `{1, 2, 3}` | ❌ No | ✅ Yes | ❌ No | Unique elements, set operations |
| **NumPy Array** | `np.array()` | ✅ Yes | ✅ Yes | ✅ Allowed | Numerical computations |

*Dictionaries maintain insertion order in Python 3.7+


---

## 3. Loops

Loops allow you to execute a block of code multiple times. Python has two main types of loops: `for` and `while`.

### For Loops

For loops are used to iterate over a sequence (list, tuple, string, range, etc.).


In [13]:
# Example 1: Iterating over a list
fruits = ['apple', 'banana', 'cherry']
print("Iterating over a list:")
for fruit in fruits:
    print(f"  - {fruit}")

# Example 2: Using range()
print("\nUsing range(5):")
for i in range(5):
    print(f"  i = {i}")

# Example 3: range with start, stop, step
print("\nUsing range(2, 10, 2):")
for i in range(2, 10, 2):
    print(f"  i = {i}")

# Example 4: Iterating with index using enumerate()
print("\nUsing enumerate():")
for index, fruit in enumerate(fruits):
    print(f"  Index {index}: {fruit}")


Iterating over a list:
  - apple
  - banana
  - cherry

Using range(5):
  i = 0
  i = 1
  i = 2
  i = 3
  i = 4

Using range(2, 10, 2):
  i = 2
  i = 4
  i = 6
  i = 8

Using enumerate():
  Index 0: apple
  Index 1: banana
  Index 2: cherry


In [68]:
# Example 3: range with start, stop, step
print("\nUsing range(2, 10, 2):")
for i in range(2, 11, 2):
    print(f"  i = {i}")


Using range(2, 10, 2):
  i = 2
  i = 4
  i = 6
  i = 8
  i = 10


In [69]:
# Example 4: Iterating with index using enumerate()
print("\nUsing enumerate():")
for index, v in enumerate(fruits):
    print(f"  Index {index}: {v}")


Using enumerate():
  Index 0: apple
  Index 1: banana
  Index 2: cherry


In [66]:
fruits = ['apple', 'banana', 'cherry']
print("Iterating over a list:")
for w in fruits:
    print(f"  - {w}")
print(fruits[2])

Iterating over a list:
  - apple
  - banana
  - cherry
cherry


### While Loops

While loops continue executing as long as a condition is True.


In [14]:
# Example 1: Basic while loop
print("Counting up with while:")
count = 0
while count < 5:
    print(f"  count = {count}")
    count += 1  # Don't forget to update the condition!

# Example 2: While loop with a different condition
print("\nCountdown:")
countdown = 5
while countdown > 0:
    print(f"  {countdown}...")
    countdown -= 1
print("  Blastoff! 🚀")


Counting up with while:
  count = 0
  count = 1
  count = 2
  count = 3
  count = 4

Countdown:
  5...
  4...
  3...
  2...
  1...
  Blastoff! 🚀


In [74]:
# Example 1: Basic while loop
print("Counting up with while:")
count3 = 0
while count3 < 5:
    print(f"  count = {count3}")
    count3 += 1  # Don't forget to update the condition!

Counting up with while:
  count = 0
  count = 1
  count = 2
  count = 3
  count = 4


---

## 4. Conditional Statements (If/Elif/Else)

Conditional statements allow your program to make decisions based on conditions.


In [15]:
# Example 1: Simple if statement
age = 20

if age >= 18:
    print("You are an adult.")

# Example 2: if-else
temperature = 15

if temperature > 25:
    print("It's hot outside!")
else:
    print("It's not too hot.")

# Example 3: if-elif-else chain
score = 85

if score >= 90:
    grade = 'A'
elif score >= 80:
    grade = 'B'
elif score >= 70:
    grade = 'C'
elif score >= 60:
    grade = 'D'
else:
    grade = 'F'

print(f"Score: {score} -> Grade: {grade}")


You are an adult.
It's not too hot.
Score: 85 -> Grade: B


In [79]:
temperature = 23

In [82]:
# Example 3: if-elif-else chain
score = 85

if score >= 90:
    grade = 'A'
elif score >= 80:
    grade = 'B'
elif score >= 70:
    grade = 'C'
elif score >= 60:
    grade = 'D'
else:
    grade = 'F'

grade    

'B'

In [16]:
# Example 4: Using logical operators (and, or, not)
age = 25
has_license = True

# Using 'and' - both conditions must be True
if age >= 18 and has_license:
    print("You can drive!")

# Using 'or' - at least one condition must be True
is_weekend = True
is_holiday = False

if is_weekend or is_holiday:
    print("Time to relax!")

# Using 'not' - inverts the boolean value
is_raining = False

if not is_raining:
    print("No need for an umbrella!")


You can drive!
Time to relax!
No need for an umbrella!


---

## 5. Loop Control: Break and Continue

Sometimes you need to control the flow within loops:
- **break**: Exit the loop entirely
- **continue**: Skip the current iteration and move to the next one


In [17]:
# Example 1: Using break - exit loop when condition is met
print("Using break - find first number divisible by 7:")
for num in range(1, 100):
    if num % 7 == 0:
        print(f"  Found: {num}")
        break  # Exit the loop immediately

# Example 2: break in a while loop - search for an item
print("\nSearching for 'banana' in the list:")
items = ['apple', 'orange', 'banana', 'grape', 'mango']
found = False

for item in items:
    print(f"  Checking: {item}")
    if item == 'banana':
        found = True
        print(f"  ✓ Found banana!")
        break

if not found:
    print("  Banana not found.")


Using break - find first number divisible by 7:
  Found: 7

Searching for 'banana' in the list:
  Checking: apple
  Checking: orange
  Checking: banana
  ✓ Found banana!


In [86]:
8 % 7

1

In [ ]:
print("Using break - find first number divisible by 7:")
for num in range(1, 100):
    if num % 7 == 0:
        print(f"  Found: {num}")
        break  # Exit the loop immediately

Using break - find first number divisible by 7:
  Found: 7
  Found: 14
  Found: 21
  Found: 28
  Found: 35
  Found: 42
  Found: 49
  Found: 56
  Found: 63
  Found: 70
  Found: 77
  Found: 84
  Found: 91
  Found: 98


In [18]:
# Example 3: Using continue - skip even numbers
print("Using continue - print only odd numbers from 1-10:")
for num in range(1, 11):
    if num % 2 == 0:  # If number is even
        continue  # Skip to next iteration
    print(f"  {num}")

# Example 4: continue with more complex logic
print("\nProcessing numbers (skip negative values):")
numbers = [5, -3, 10, -1, 8, -7, 3]
total = 0

for num in numbers:
    if num < 0:
        print(f"  Skipping negative number: {num}")
        continue
    total += num
    print(f"  Added {num}, running total: {total}")

print(f"\nFinal total (only positive numbers): {total}")


Using continue - print only odd numbers from 1-10:
  1
  3
  5
  7
  9

Processing numbers (skip negative values):
  Added 5, running total: 5
  Skipping negative number: -3
  Added 10, running total: 15
  Skipping negative number: -1
  Added 8, running total: 23
  Skipping negative number: -7
  Added 3, running total: 26

Final total (only positive numbers): 26


In [89]:
# Example 3: Using continue - skip even numbers
print("Using continue - print only odd numbers from 1-10:")
for num in range(1, 11):
    if num % 2 == 0:  # If number is even
        #continue  # Skip to next iteration
        print(num)
    print(f"  {num}")

Using continue - print only odd numbers from 1-10:
  1
2
  2
  3
4
  4
  5
6
  6
  7
8
  8
  9
10
  10


---

## 6. User-Defined Functions

Functions are reusable blocks of code that perform a specific task. They help organize code and avoid repetition.

### Basic Function Syntax

```python
def function_name(parameters):
    """Docstring: describes what the function does"""
    # Function body
    return result  # Optional
```


In [19]:
# Example 1: Simple function with no parameters
def greet():
    """Prints a greeting message."""
    print("Hello, World!")

greet()

# Example 2: Function with parameters
def greet_person(name):
    """Greets a person by name."""
    print(f"Hello, {name}!")

greet_person("Alice")
greet_person("Bob")

# Example 3: Function with return value
def add_numbers(a, b):
    """Returns the sum of two numbers."""
    return a + b

result = add_numbers(5, 3)
print(f"5 + 3 = {result}")


Hello, World!
Hello, Alice!
Hello, Bob!
5 + 3 = 8


In [20]:
# Example 4: Function with default parameters
def power(base, exponent=2):
    """Raises base to the power of exponent. Default is squared."""
    return base ** exponent

print(f"3 squared: {power(3)}")        # Uses default exponent=2
print(f"2 cubed: {power(2, 3)}")       # Override default

# Example 5: Function with multiple return values
def get_stats(numbers):
    """Returns min, max, and average of a list of numbers."""
    minimum = min(numbers)
    maximum = max(numbers)
    average = sum(numbers) / len(numbers)
    return minimum, maximum, average

data = [10, 20, 30, 40, 50]
min_val, max_val, avg_val = get_stats(data)
print(f"\nStats for {data}:")
print(f"  Min: {min_val}, Max: {max_val}, Average: {avg_val}")

# Example 6: Function with keyword arguments
def describe_pet(animal_type, pet_name, age=None):
    """Displays information about a pet."""
    description = f"I have a {animal_type} named {pet_name}"
    if age:
        description += f" who is {age} years old"
    print(description + ".")

describe_pet("dog", "Max")
describe_pet(pet_name="Whiskers", animal_type="cat", age=3)


3 squared: 9
2 cubed: 8

Stats for [10, 20, 30, 40, 50]:
  Min: 10, Max: 50, Average: 30.0
I have a dog named Max.
I have a cat named Whiskers who is 3 years old.


---

## 7. Classes (Object-Oriented Programming)

Classes are blueprints for creating objects. They bundle data (attributes) and functionality (methods) together.

### Basic Class Syntax

```python
class ClassName:
    def __init__(self, parameters):
        """Constructor: initializes the object"""
        self.attribute = parameters
    
    def method(self):
        """A method that operates on the object"""
        pass
```


In [21]:
# Example 1: A simple Dog class
class Dog:
    """A simple Dog class."""

    def __init__(self, name, age):
        """Initialize name and age attributes."""
        self.name = name
        self.age = age

    def bark(self):
        """Simulate the dog barking."""
        print(f"{self.name} says: Woof! 🐕")

    def describe(self):
        """Print a description of the dog."""
        print(f"{self.name} is {self.age} years old.")

# Creating instances (objects) of the Dog class
my_dog = Dog("Buddy", 3)
your_dog = Dog("Luna", 5)

# Accessing attributes
print(f"My dog's name: {my_dog.name}")
print(f"Your dog's age: {your_dog.age}")

# Calling methods
my_dog.bark()
your_dog.describe()


My dog's name: Buddy
Your dog's age: 5
Buddy says: Woof! 🐕
Luna is 5 years old.


In [22]:
# Example 2: A more practical BankAccount class
class BankAccount:
    """A class representing a bank account."""

    def __init__(self, owner, balance=0):
        """Initialize the account with owner name and starting balance."""
        self.owner = owner
        self.balance = balance
        print(f"Account created for {owner} with balance: ${balance:.2f}")

    def deposit(self, amount):
        """Add money to the account."""
        if amount > 0:
            self.balance += amount
            print(f"Deposited: ${amount:.2f}. New balance: ${self.balance:.2f}")
        else:
            print("Deposit amount must be positive!")

    def withdraw(self, amount):
        """Remove money from the account if sufficient funds exist."""
        if amount > self.balance:
            print(f"Insufficient funds! Available: ${self.balance:.2f}")
        elif amount <= 0:
            print("Withdrawal amount must be positive!")
        else:
            self.balance -= amount
            print(f"Withdrew: ${amount:.2f}. New balance: ${self.balance:.2f}")

    def get_balance(self):
        """Return the current balance."""
        return self.balance

# Using the BankAccount class
account = BankAccount("Alice", 100)
account.deposit(50)
account.withdraw(30)
account.withdraw(200)  # Should fail
print(f"\nFinal balance: ${account.get_balance():.2f}")


Account created for Alice with balance: $100.00
Deposited: $50.00. New balance: $150.00
Withdrew: $30.00. New balance: $120.00
Insufficient funds! Available: $120.00

Final balance: $120.00


### Class Inheritance

Inheritance allows you to create a new class based on an existing class, inheriting its attributes and methods.


In [23]:
# Example 3: Inheritance - Parent class
class Animal:
    """Base class for all animals."""

    def __init__(self, name, species):
        self.name = name
        self.species = species

    def make_sound(self):
        print(f"{self.name} makes a sound.")

    def describe(self):
        print(f"{self.name} is a {self.species}.")

# Child class that inherits from Animal
class Cat(Animal):
    """Cat class that inherits from Animal."""

    def __init__(self, name, color):
        # Call the parent class constructor
        super().__init__(name, species="Cat")
        self.color = color

    # Override the parent method
    def make_sound(self):
        print(f"{self.name} says: Meow! 🐱")

    # Add a new method specific to Cat
    def purr(self):
        print(f"{self.name} is purring...")

# Using the classes
generic_animal = Animal("Generic", "Unknown")
generic_animal.make_sound()
generic_animal.describe()

print()  # Empty line

my_cat = Cat("Mittens", "orange")
my_cat.make_sound()  # Uses the overridden method
my_cat.describe()    # Uses inherited method from Animal
my_cat.purr()        # Uses Cat-specific method


Generic makes a sound.
Generic is a Unknown.

Mittens says: Meow! 🐱
Mittens is a Cat.
Mittens is purring...


---

## Summary

In this notebook, we covered the fundamental building blocks of Python programming:

| Topic | Key Concepts |
|-------|--------------|
| **Libraries** | `import`, `import as`, `from ... import` |
| **For Loops** | `for item in sequence`, `range()`, `enumerate()` |
| **While Loops** | `while condition:`, loop control |
| **Conditionals** | `if`, `elif`, `else`, `and`, `or`, `not` |
| **Loop Control** | `break` (exit loop), `continue` (skip iteration) |
| **Functions** | `def`, parameters, `return`, default values |
| **Classes** | `class`, `__init__`, `self`, methods, inheritance |

---
